<?php require_once './templates/header.phtml' ?>

<form method='POST' action='formAgregarProducto'>
    <div class="form-group">
    	<label for="nombreCategoria">product_id</label>
      <input type="text" class="form-control" placeholder="id del nuevo producto" id="product_id" name='product_id'>
    </div>
      <label for="nombreCategoria">Nombre</label>
      <input type="text" class="form-control" placeholder="Nombre del nuevo producto" id="name" name='name'>
    </div>
    <div class="form-group">
      <label for="nombreCategoria">precio</label>
      <input type="text" class="form-control" placeholder="precio del nuevo producto" id="price" name='price'>
    </div>
    <div class="form-group">
      <label for="nombreCategoria">stock</label>
      <input type="text" class="form-control" placeholder="Stock del nuevo producto" id="stock" name='stock'>
    </div>
    <div class="form-group">
      <label for="nombreCategoria">CategoryId</label>
      <select class="form-control" name='CategoryId' id='CategoryId'>
            <?php foreach($category as $categorys): ?>
            <option><?= $categorys->CategoryId?></option>
            <?php endforeach ?>
        </select>
    </div>
    </div><div class="form-group">
        <label for="imagen">Imagen</label>
        <input type="text" class="form-control" id="imagen" name='image' placeholder="Inserte el link de la imagen">
    </div>

    <button type="submit" class="btn btn-primary">Agregar</button>
    
    
</form>

<?php if ($message != null): ?>
    <div class="alert alert-danger" role='alert'>
        <p><?= $message ?></p>
    </div>
    <?php endif ?>

<?php require_once './templates/footer.phtml' ?>