<main class="main-administrar">
    
    <div class="administrar-info">
        <div class="logo-info">
            <i class="fa-solid fa-info fa-sm"></i>
        </div>
        <h4>Aclaración:</h4>
        <p>Los botones de arriba de los formularios cambian las funciones de los mismos. Consultar la tabla del final de la pagina para saber el id del producto o categoria que desea editar o eliminar.</p>
    </div>

     <div class="form-type">
        <input class="btns-admin" type="button" value="Editar" number="1">
        <input class="btns-admin" type="button" value="Agregar" number="2">
        <input class="btns-admin" type="button" value="Eliminar" number="3">
    </div>

    <form action="agregarProducto" method="POST" class="form" id="form-productos">
        <p class="form-title" id="form-title-productos">Agregar Producto</p>

        <div class="mb-3" >
            <label for="exampleFormControlInput" class="form-label">Seleccione el id de un producto</label>
            <select class="form-select" aria-label="Default select example">
                <?php foreach ($products as $product) : ?>
                    <option value="<?= $product->product_id ?>"><?= $product->product_id ?></option>
                <?php endforeach ?>
            </select>
        </div>

        <div class="" id="cont-form-productos">
            <div class="form-input__container">
                <label>Nombre del producto</label>
                <input name="name" type="text" class="form-control">
            </div>

            <div class="form-input__container">
                <label>Precio</label>
                <input type="number" name="price" class="form-control"></input>
            </div>

            <div class="form-input__container">
                <label>Stock</label>
                <input type="number" name="stock" class="form-control"></input>
            </div>

            <div class="form-select__conteiner select-width">
                <label>Categoria</label>
                <select required name="CategoryId" class="form-select" aria-label="Default select example">
                    <?php foreach ($category as $category) : ?>
                        <option value="<?= $category->CategoryId ?>"><?= $category->type ?></option>
                    <?php endforeach ?>
                </select>
            </div>
        </div>

        <button action="administrar" type="submit" class="form-submit" id="btn-submit-productos">Enviar</button>
    </form>

    <div class="form-type">
        <input class="btns-admin" type="button" value="Editar" number="4">
        <input class="btns-admin" type="button" value="Agregar" number="5">
        <input class="btns-admin" type="button" value="Eliminar" number="6">
    </div>

    <form action="agregarCategoria" class="form" method="POST" id="form-categorias">
        <p class="form-title" id="form-title-categorias">Agregar Categoria</p>

        <div class="noMostrar" id="select-ids-categorias">
            <label for="CategoryId">Seleccione una categoria</label>
    
            <p id="p-eliminar-producto">Recuerde que para eliminar la catogoria, esta no debe tener productos.</p>
            <select name="CategoryId">
                <?php foreach ($categorys as $category) : ?>
                    <option value="<?= $category->CategoryId ?>"><?= $category->type ?></option>
                <?php endforeach ?>
            </select>
        </div>

        <div class="" id="cont-form-categorias">
            <div class="form-input__container">
                <label>Nombre de la categoria</label>
                <input name="Category_name" type="text" class="form-control">
            </div>
        </div>

        <button action="administrar" type="submit" class="form-submit" id="btn-submit-categorias">Enviar</button>
    </form>

    <div class="tabla-container">
        <h3>Info de los Productos</h3>
        <p>Tabla para mostrar información y eliminar productos de la base de datos</p>
        <table>
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Producto</th>
                    <th>Precio</th>
                    <th>Stock</th>
                    <th>Categoria</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($products as $product) : ?>
                    <tr>
                        <td><?= $product->product_id ?></td>
                        <td><?= $product->name ?></td>
                        <td>$<?= $product->price ?></td>
                        <td>$<?= $product->stock ?></td>
                    </tr>
                <?php endforeach ?>
            </tbody>
        </table>
    </div>
</main>
<script src="js/administrar.js"></script>
<script src="js/main.js"></script>
</body>

</html>