<?php require_once './templates/header.phtml' ?>

<form method='POST' action="/web2/web2-tpe/editarProducto/<?= $product->product_id ?>">
    <div class="form-group">
      <label for="nombreProducto">Nombre</label> 
      <input type="text" class="form-control" id="name" name='name' placeholder="Nombre del Producto" value='<?= $product->name ?>'>
    </div>
    <div class="form-group">
      <label for="precioProducto">Precio</label>
      <input type="text" class="form-control" id="price" name='price' placeholder="Precio del Producto" value='<?= $product->price ?>'>
    </div>
    <div class="form-group">
      <label for="stockProducto">Stock</label>
      <input type="text" class="form-control" id="stock" name='stock' placeholder="Stock del Producto" value='<?= $product->stock ?>'>
    </div>
    <div class="form-group">
      <label for="categoryProducto">CategoryId</label>
       <select class="form-control" name='CategoryId' id='CategoryId' value='<?= $product->CategoryId ?>'>
            <?php foreach($category as $categorys): ?>
            <option><?= $categorys->CategoryId?></option>
            <?php endforeach ?>
        </select>
    </div>
   <button type="submit" class="btn btn-primary">Editar</button>

   <?php if ($message != null): ?>
    	<div class="alert alert-danger" role='alert'>
        	<p><?= $message ?></p>
    	</div>
    <?php endif ?>
</form> 


<?php require_once './templates/footer.phtml' ?>