<?php require 'templates/header.phtml';?>
<main class="main-form__inicioSesion">
	<form action="registro" method="POST" class="form">
		<p class="form-title">Ingrese a su cuentaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa</p>

		<div class="form-input__container">
			<input name="name" placeholder="Nombre">
		</div>

		<div class="form-input__container">
			<input name="email_user" placeholder="Email">
		</div>


		<div class="form-input__container">
			<input name="password" type="password" placeholder="Contraseña">
		</div>

		<!– cartel error de datos incorrectos/vacíos –>

		<?php if ($error) : ?> 
			<div class="alert alert-danger" role='alert'>
				<?= $error ?>
			</div>
		<?php endif ?>

		<button type="submit" class="form-submit">
			registrar
		</button>

	</form>
</main>
<?php require 'templates/footer.phtml'; ?> 