<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <base href="<?= BASE_URL ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" type="text/css" href="css/style.css">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
    <header>
        <div class="logo">
			<img class="logoimg" src="img/4899991239217120768_1.png">
		 	<div class="btn_menu"><a>MENÚ</a></div>
		</div>
		<nav class="menu">
		  <ul class="barradenav">
			   <li><a href="home">Home</a></li>
			   <li><a href="productos">Tienda</a></li>
			   <li><a href="inicioSesion">Administrar</a></li>
			   	<?php if (!AuthHelper::isLogged()) : ?>
                   <li class="nav-item">
                      <a class="nav-link" aria-current="page" href="inicioSesion">Login</a>
                   </li>
                <?php else : ?>
                   <li class="nav-item">
                       <a class="nav-link" aria-current="page" href="logout">Logout</a>
                   </li>
                <?php endif ?> 
		   </ul>
        </nav>
    </header>
    <script src="js/navbar.js"></script>