<main>
<div class = "row ">
            <?php foreach ($products as $products) {
              ?>
                <div class = "col-lg-3 img-thumbnail" >
                        <h3><?= $products->name?></h3>
                        <p>Precio: <?= $products->price?></p>
                        <p>Stock: <?= $products->stock?></p>
                </div>
        <?php
    
            }
?>
</div>
</main>
